name: Context Example

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      -name: "My steps"
      run: echo "Hello! $MY_ACTION"
      env:
        MY_ACTION: ${{ github.action }}